spring.application.name=auth-service
server.port=8084
#Cấu hình cho phép BE gửi lỗi chi tiết cho FE (????)
server.error.include-message=always 

eureka.instance.prefer-ip-address=true

# Database configuration (MariaDB)
spring.datasource.url=jdbc:mariadb://localhost:3306/enjoy_auth_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=enjoy.support.team@gmail.com
spring.mail.password=bbrnujuofdqxcsos
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.signerKey=qkqwyKZxDFIyakJVrxojGYa66ShVokq8gofJ1v2zCLeM3o38gDb0E7z9vLVNeW47EYSQVoZI5dds4TLsHIDGW0